name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm build
    - run: |
        git config user.name Shmueli Englard
        git config user.email shmueli.yosef@englard.net
        git checkout --progress gh-pages
        cp ./dist/* ./
        git add .
        git commit --allow-empty -m "Updating GH Pages"
        git push