name: Node.js CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build site on Ubuntu using NodeJS 18.x
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    - name: Install PNPM globally
      run: npm install -g pnpm
    - name: Install dependencies and confure build
      run: pnpm install
    - name: Build Site
      run: pnpm build
    - name: Configure git
      run: |
        git config user.name Shmueli Englard
        git config user.email shmueli.yosef@englard.net
    - name: Checkout Github Pages branch
      run: |
        git checkout --force --progress gh-pages
    - name: Clear root directory
      run: rm -f ./*.*
    - name: Copy build output to root directory
      run: cp -r ./dist/* ./
    - name: Add changes to git
      run: git add .
    - name: Commit changes to git
      run: git commit --allow-empty -m "Updating GH Pages"
    - name: Push git changes.
      run: git push